# Generated by Django 3.0.5 on 2020-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_sellertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellertoken',
            name='access_token',
            field=models.TextField(),
        ),
    ]
