# Generated by Django 3.0.5 on 2020-04-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20200425_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('shipment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pick_up_point', models.BooleanField()),
                ('shipment_date', models.DateTimeField()),
                ('shipment_reference', models.BigIntegerField()),
                ('transport_id', models.BigIntegerField()),
                ('transporter_code', models.TextField()),
                ('track_and_trace', models.TextField()),
                ('salutation_code', models.BigIntegerField()),
                ('zip_code', models.TextField()),
                ('country_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField()),
                ('order_date', models.DateTimeField()),
                ('latest_delivery_date', models.DateTimeField()),
                ('ean', models.BigIntegerField()),
                ('title', models.TextField()),
                ('quantity', models.BigIntegerField()),
                ('offer_price', models.BigIntegerField()),
                ('offer_condition', models.TextField()),
                ('offer_reference', models.TextField()),
                ('fulfillment_method', models.TextField()),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.ShipmentDetails')),
            ],
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sync_in_progress', models.BooleanField()),
                ('sync_start_time', models.DateTimeField()),
                ('sync_end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
