# Generated by Django 3.0.5 on 2020-04-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20200425_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdetails',
            name='email',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='shipment_reference',
            field=models.BigIntegerField(default=None),
        ),
    ]
