# Generated by Django 3.0.5 on 2020-04-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_auto_20200425_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='order_item_id',
            field=models.TextField(),
        ),
    ]
