# Generated by Django 3.0.5 on 2020-04-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_auto_20200426_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentIdSyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.BigIntegerField()),
                ('sync_in_progress', models.BooleanField()),
            ],
        ),
    ]
